from typing import Any


class Evaluator:
    """
    Evaluator evaluates answers generated by attempts. The results of the
    evaluation is used by metric calculators.

    The class is used as a key when the results of the evaluation are stored in 
    an attempt.
    """

    def evaluate(self, attempt) -> Any:
        raise NotImplementedError

    def __call__(self, attempt) -> Any:
        return self.evaluate(attempt)
